// web/src/components/ui/checkbox.tsx
'use client'

import { Checkbox } from '@base-ui/react/checkbox'
import { CheckIcon } from 'lucide-react'
import type * as React from 'react'

import { cn } from '@/lib/utils'

function CheckboxComponent({ className, ...props }: React.ComponentProps<typeof Checkbox.Root>) {
  return (
    <Checkbox.Root
      data-slot="checkbox"
      className={cn(
        'peer border-input dark:bg-input/30 data-[checked]:bg-primary data-[checked]:text-primary-foreground dark:data-[checked]:bg-primary data-[checked]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50',
        className
      )}
      {...props}
    >
      <Checkbox.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none"
      >
        <CheckIcon className="size-3.5" />
      </Checkbox.Indicator>
    </Checkbox.Root>
  )
}

export { CheckboxComponent as Checkbox }

// qwik-app/src/components/ui/checkbox/checkbox.tsx
import { $, type PropsOf, component$ } from "@builder.io/qwik";
import { cn } from "@qwik-ui/utils";

export const Checkbox = component$<
  Partial<PropsOf<"input"> & { type?: "checkbox" }>
>(({ id, name, ["bind:checked"]: bindSig, checked, onInput$, ...props }) => {
  const inputId = id || name;
  return (
    <input
      {...props}
      type="checkbox"
      // workaround to support two way data-binding on the Input component (https://github.com/QwikDev/qwik/issues/3926)
      checked={bindSig ? bindSig.value : checked}
      onInput$={[
        bindSig && $((_, el) => (bindSig.value = el.checked)),
        onInput$,
      ]}
      data-checked={checked || bindSig?.value || ""}
      class={cn(
        "peer border-primary text-primary accent-primary ring-offset-background focus:ring-ring focus-visible:ring-ring h-4 w-4 shrink-0 disabled:cursor-not-allowed disabled:opacity-50",
        props.class,
      )}
      id={inputId}
      name={name}
    />
  );
});
