// web/src/components/navigation.tsx
"use client";

import { cva, type VariantProps } from "class-variance-authority";
import { AnimatePresence, motion } from "framer-motion";
import { Menu, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { ContactDialog } from "@/components/contact-dialog";
import { cn } from "@/lib/utils";

const navItemVariants = cva(
  "flex items-center justify-center rounded-md backdrop-blur-sm bg-stone-200/70 text-[11px] font-twk font-normal leading-tight transition-colors hover:text-foreground",
  {
    variants: {
      size: {
        brand: "h-7 w-[75px]",
        default: "h-7 w-[75px]",
        mobile: "h-7 w-[52px]",
        mobileWide: "h-7 w-[62px]",
        icon: "h-7 w-7",
      },
      active: {
        true: "text-foreground",
        false: "text-muted-foreground",
      },
    },
    defaultVariants: {
      size: "default",
      active: false,
    },
  },
);

type NavItemVariantProps = VariantProps<typeof navItemVariants>;

interface NavigationProps {
  variant?: "default" | "ai";
  isLoomPage?: boolean;
  onClear?: () => void;
}

export function Navigation({
  variant = "default",
  isLoomPage = false,
  onClear,
}: NavigationProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [contactDialogOpen, setContactDialogOpen] = useState(false);
  const pathname = usePathname();
  const isAIVariant = variant === "ai";

  useEffect(() => {
    const saved = sessionStorage.getItem("mobileMenuOpen");
    if (saved === "true") {
      setIsOpen(true);
    }
  }, []);

  useEffect(() => {
    sessionStorage.setItem("mobileMenuOpen", isOpen.toString());
  }, [isOpen]);

  const handleContactClick = () => {
    setContactDialogOpen(true);
  };

  return (
    <nav className="fixed top-[15px] left-0 right-0 z-[60] px-3 pointer-events-none">
      {/* Mobile Navigation (or AI variant) */}
      <div
        className={cn(
          "flex items-center gap-[6px] w-full pointer-events-auto relative z-50",
          isAIVariant ? "" : "sm:hidden",
        )}
      >
        {/* Hamburger/X Button */}
        <button
          type="button"
          onClick={() => setIsOpen(!isOpen)}
          data-slot="nav-item"
          className={cn(navItemVariants({ size: "icon" }), "text-foreground")}
          aria-label="Toggle menu"
        >
          <AnimatePresence mode="wait">
            {isOpen ? (
              <motion.div
                key="x-icon"
                initial={{ opacity: 0, rotate: -90 }}
                animate={{ opacity: 1, rotate: 0 }}
                exit={{ opacity: 0, rotate: 90 }}
                transition={{ duration: 0.2 }}
              >
                <X size={16} strokeWidth={1.5} />
              </motion.div>
            ) : (
              <motion.div
                key="menu-icon"
                initial={{ opacity: 0, rotate: 90 }}
                animate={{ opacity: 1, rotate: 0 }}
                exit={{ opacity: 0, rotate: -90 }}
                transition={{ duration: 0.2 }}
              >
                <Menu size={16} strokeWidth={1.5} />
              </motion.div>
            )}
          </AnimatePresence>
        </button>

        <AnimatePresence mode="wait">
          {!isOpen && (
            <motion.div
              key="otherdev-pill"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.8 }}
              transition={{ duration: 0.2 }}
            >
              <Link
                href="/"
                data-slot="nav-item"
                className={cn(
                  navItemVariants({ size: "brand", active: pathname === "/" }),
                )}
              >
                Other dev
              </Link>
            </motion.div>
          )}
        </AnimatePresence>

        <AnimatePresence mode="wait">
          {isOpen && (
            <motion.div
              key="menu-open"
              className="flex items-center gap-1.5 flex-1"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
            >
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1, duration: 0.3 }}
              >
                <Link
                  href="/work"
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({
                      size: "mobile",
                      active: pathname?.startsWith("/work"),
                    }),
                  )}
                >
                  Work
                </Link>
              </motion.div>
              {/* <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.15, duration: 0.3 }}
              >
                <Link
                  href="/audio"
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({
                      size: "mobile",
                      active: pathname?.startsWith("/audio"),
                    }),
                  )}
                >
                  audio
                </Link>
              </motion.div> */}
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2, duration: 0.3 }}
              >
                <Link
                  href="/about"
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({
                      size: "mobile",
                      active: pathname?.startsWith("/about"),
                    }),
                  )}
                >
                  About
                </Link>
              </motion.div>
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.25, duration: 0.3 }}
              >
                <Link
                  href="/loom"
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({
                      size: "mobile",
                      active: pathname?.startsWith("/loom"),
                    }),
                  )}
                >
                  Ai
                </Link>
              </motion.div>
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.27, duration: 0.3 }}
              >
                <button
                  type="button"
                  onClick={handleContactClick}
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({ size: "mobileWide", active: false }),
                  )}
                >
                  Contact
                </button>
              </motion.div>
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.32, duration: 0.3 }}
              >
                <Link
                  href="https://wa.me/923156893331?text=Hi!%20I%20found%20you%20through%20otherdev.com%20and%20would%20love%20to%20discuss%20a%20project."
                  target="_blank"
                  rel="noopener noreferrer"
                  data-slot="nav-item"
                  className={cn(
                    navItemVariants({ size: "mobileWide", active: false }),
                  )}
                >
                  Whatsapp
                </Link>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Tablet/Desktop Navigation */}
      {!isAIVariant && (
        <div className="hidden sm:flex items-center gap-1.5 pointer-events-auto">
          <Link
            href="/"
            data-slot="nav-item"
            className={cn(
              navItemVariants({ size: "brand", active: pathname === "/" }),
            )}
          >
            Other dev
          </Link>
          <Link
            href="/work"
            data-slot="nav-item"
            className={cn(
              navItemVariants({
                size: "default",
                active: pathname?.startsWith("/work"),
              }),
            )}
          >
            Work
          </Link>
          {/* <Link
          href="/audio"
          data-slot="nav-item"
          className={cn(
            navItemVariants({
              size: "default",
              active: pathname?.startsWith("/audio"),
            }),
          )}
        >
          audio
        </Link> */}
          <Link
            href="/about"
            data-slot="nav-item"
            className={cn(
              navItemVariants({
                size: "default",
                active: pathname?.startsWith("/about"),
              }),
            )}
          >
            About
          </Link>
          <Link
            href="/loom"
            data-slot="nav-item"
            className={cn(
              navItemVariants({
                size: "default",
                active: pathname?.startsWith("/loom"),
              }),
            )}
          >
            Ai
          </Link>
          <button
            type="button"
            onClick={handleContactClick}
            data-slot="nav-item"
            className={cn(navItemVariants({ size: "default", active: false }))}
          >
            Contact
          </button>
          <Link
            href="https://wa.me/923156893331?text=Hi!%20I%20found%20you%20through%20otherdev.com%20and%20would%20love%20to%20discuss%20a%20project."
            target="_blank"
            rel="noopener noreferrer"
            data-slot="nav-item"
            className={cn(navItemVariants({ size: "default", active: false }))}
          >
            Whatsapp
          </Link>
        </div>
      )}

      {/* Clear Chat Button */}
      {isLoomPage && onClear && (
        <button
          type="button"
          onClick={onClear}
          className={cn(
            navItemVariants({ size: "default" }),
            "absolute right-3 top-0 pointer-events-auto",
            "bg-red-50/70 text-red-600 hover:text-red-700 hover:bg-red-100/70",
          )}
        >
          Clear
        </button>
      )}

      {/* Backdrop */}
      {isOpen && (
        <div
          className={cn(
            "fixed inset-0 z-30 -backdrop-blur-lg pointer-events-none",
            isAIVariant ? "" : "sm:hidden",
          )}
        />
      )}

      {/* Contact Dialog */}
      <ContactDialog
        open={contactDialogOpen}
        onOpenChange={setContactDialogOpen}
      />
    </nav>
  );
}

export { navItemVariants };

// qwik-astro-app/src/components/navigation.tsx
/** @jsxImportSource react */
import { qwikify$ } from '@builder.io/qwik-react'
import { Menu, X } from 'lucide-react'
import { useState } from 'react'
import { cn } from '@/lib/utils'

interface NavigationProps {
  variant?: 'default' | 'ai'
  isLoomPage?: boolean
}

function NavigationComponent({ variant = 'default', isLoomPage = false }: NavigationProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [pathname] = useState(typeof window !== 'undefined' ? window.location.pathname : '/')
  const isAIVariant = variant === 'ai'

  const navLinks = [
    { href: '/work', label: 'work' },
    { href: '/about', label: 'about' },
    { href: '/loom', label: 'ai' },
    { href: '/work/ads-portfolio', label: 'ads' },
  ]

  return (
    <nav className={cn(
      'fixed top-[15px] left-0 right-0 z-[60] px-3 pointer-events-none',
      isAIVariant ? '' : 'sm:block'
    )}>
      {/* Mobile Navigation */}
      <div
        className={cn(
          'flex items-center justify-between w-full pointer-events-auto relative z-50',
          isAIVariant ? '' : 'sm:hidden'
        )}
      >
        {/* Logo pill - hidden when menu open */}
        <div
          className={cn(
            'transition-all duration-200 origin-left',
            !isOpen ? 'opacity-100 scale-100' : 'opacity-0 scale-75 pointer-events-none'
          )}
        >
          <a
            href="/"
            className={cn(
              'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
              'backdrop-blur-sm bg-stone-200/70',
              'text-muted-foreground hover:text-foreground',
              pathname === '/' && 'text-foreground'
            )}
          >
            other dev
          </a>
        </div>

        {/* Menu button and links container */}
        <div className="flex items-center gap-1.5 ml-auto">
          {/* Nav links - visible when menu open */}
          <div
            className={cn(
              'flex items-center gap-1.5 mr-2 transition-all duration-200',
              isOpen ? 'opacity-100 translate-x-0' : 'opacity-0 translate-x-4 pointer-events-none'
            )}
          >
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className={cn(
                  'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
                  'backdrop-blur-sm bg-stone-200/70',
                  'text-muted-foreground hover:text-foreground',
                  pathname.startsWith(link.href) && 'text-foreground'
                )}
              >
                {link.label}
              </a>
            ))}
            <a
              href="https://wa.me/923156893331?text=Hi!%20I%20found%20you%20through%20otherdev.com%20and%20would%20love%20to%20discuss%20a%20project."
              target="_blank"
              rel="noopener noreferrer"
              className={cn(
                'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
                'backdrop-blur-sm bg-stone-200/70',
                'text-muted-foreground hover:text-foreground'
              )}
            >
              whatsapp
            </a>
          </div>

          {/* Hamburger/X Button */}
          <button
            onClick={() => setIsOpen(!isOpen)}
            aria-label="Toggle menu"
            className={cn(
              'h-[25px] w-[25px] flex items-center justify-center rounded-full transition-colors',
              'text-muted-foreground hover:text-foreground hover:bg-stone-200/50'
            )}
          >
            <div
              className={cn(
                'absolute transition-all duration-200',
                isOpen ? 'opacity-100 rotate-0' : 'opacity-0 rotate-90'
              )}
            >
              <X size={16} strokeWidth={1.5} />
            </div>
            <div
              className={cn(
                'transition-all duration-200',
                isOpen ? 'opacity-0 -rotate-90' : 'opacity-100 rotate-0'
              )}
            >
              <Menu size={16} strokeWidth={1.5} />
            </div>
          </button>
        </div>
      </div>

      {/* Desktop Navigation */}
      {!isAIVariant && (
        <div className="hidden sm:flex items-center gap-1.5 pointer-events-auto">
          <a
            href="/"
            className={cn(
              'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
              'backdrop-blur-sm bg-stone-200/70',
              'text-muted-foreground hover:text-foreground',
              pathname === '/' && 'text-foreground'
            )}
          >
            other dev
          </a>
          {navLinks.map(link => (
            <a
              key={link.href}
              href={link.href}
              className={cn(
                'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
                'backdrop-blur-sm bg-stone-200/70',
                'text-muted-foreground hover:text-foreground',
                pathname.startsWith(link.href) && 'text-foreground'
              )}
            >
              {link.label}
            </a>
          ))}
          <a
            href="https://wa.me/923156893331?text=Hi!%20I%20found%20you%20through%20otherdev.com%20and%20would%20love%20to%20discuss%20a%20project."
            target="_blank"
            rel="noopener noreferrer"
            className={cn(
              'h-[25px] px-3 py-1.5 text-[11.4px] font-twk rounded-full transition-colors',
              'backdrop-blur-sm bg-stone-200/70',
              'text-muted-foreground hover:text-foreground'
            )}
          >
            whatsapp
          </a>
        </div>
      )}

      {/* Backdrop */}
      {isOpen && (
        <div
          className={cn(
            'fixed inset-0 z-30 backdrop-blur-lg pointer-events-none',
            isAIVariant ? '' : 'sm:hidden'
          )}
        />
      )}
    </nav>
  )
}

export const Navigation = qwikify$(NavigationComponent)
