// qwik-app/src/components/ui/collapsible/collapsible.tsx
import { component$, Slot, type PropsOf } from "@builder.io/qwik";
import { Collapsible as HeadlessCollapsible } from "@qwik-ui/headless";
import { cn } from "@qwik-ui/utils";

const Root = (props: PropsOf<typeof HeadlessCollapsible.Root>) => (
  <HeadlessCollapsible.Root {...props}>
    {props.children}
  </HeadlessCollapsible.Root>
);

const Trigger = component$<PropsOf<typeof HeadlessCollapsible.Trigger>>(
  ({ ...props }) => {
    return (
      <HeadlessCollapsible.Trigger {...props}>
        <Slot />
      </HeadlessCollapsible.Trigger>
    );
  },
);

const Content = component$<PropsOf<typeof HeadlessCollapsible.Content>>(
  (props) => {
    return (
      <HeadlessCollapsible.Content {...props} class={cn(props.class)}>
        <Slot />
      </HeadlessCollapsible.Content>
    );
  },
);

export const Collapsible = {
  Root,
  Trigger,
  Content,
};

// web/src/components/ui/collapsible.tsx
'use client'

import { Collapsible } from '@base-ui/react/collapsible'
import type * as React from 'react'

function CollapsibleRoot({ ...props }: React.ComponentProps<typeof Collapsible.Root>) {
  return <Collapsible.Root data-slot="collapsible" {...props} />
}

function CollapsibleTrigger({ ...props }: React.ComponentProps<typeof Collapsible.Trigger>) {
  return <Collapsible.Trigger data-slot="collapsible-trigger" {...props} />
}

function CollapsibleContent({ ...props }: React.ComponentProps<typeof Collapsible.Panel>) {
  return <Collapsible.Panel data-slot="collapsible-content" {...props} />
}

export { CollapsibleRoot as Collapsible, CollapsibleTrigger, CollapsibleContent }
