// qwik-app/src/components/ui/popover/popover.tsx
import { type PropsOf, Slot, component$ } from "@builder.io/qwik";
import { Popover as HeadlessPopover } from "@qwik-ui/headless";
import { cn } from "@qwik-ui/utils";

const Root = component$<PropsOf<typeof HeadlessPopover.Root>>(
  ({ ...props }) => {
    return (
      <HeadlessPopover.Root {...props}>
        <Slot />
      </HeadlessPopover.Root>
    );
  },
);

const Trigger = HeadlessPopover.Trigger;

const Panel = component$<PropsOf<typeof HeadlessPopover.Panel>>(
  ({ ...props }) => {
    return (
      <HeadlessPopover.Panel
        {...props}
        class={cn(
          "my-transition bg-popover text-popover-foreground w-72 rounded-md border p-4 shadow-md outline-hidden",
          "data-closing:animate-out data-closing:zoom-out-95 data-closing:fade-out data-open:animate-in data-open:zoom-in-95 data-open:fade-in",
          "data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2",
          props.class,
        )}
      >
        <Slot />
      </HeadlessPopover.Panel>
    );
  },
);

export const Popover = {
  Root,
  Trigger,
  Panel,
};

// web/src/components/ui/popover.tsx
'use client'

import { Popover } from '@base-ui/react/popover'
import type * as React from 'react'

import { cn } from '@/lib/utils'

function PopoverRoot({ ...props }: React.ComponentProps<typeof Popover.Root>) {
  return <Popover.Root data-slot="popover" {...props} />
}

function PopoverTrigger({ ...props }: React.ComponentProps<typeof Popover.Trigger>) {
  return <Popover.Trigger data-slot="popover-trigger" {...props} />
}

function PopoverContent({
  className,
  align = 'center',
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof Popover.Popup> & {
  align?: 'start' | 'center' | 'end'
  sideOffset?: number
}) {
  return (
    <Popover.Portal>
      <Popover.Positioner align={align} sideOffset={sideOffset}>
        <Popover.Popup
          data-slot="popover-content"
          className={cn(
            'bg-popover text-popover-foreground data-[open]:animate-in data-[closed]:animate-out data-[closed]:fade-out-0 data-[open]:fade-in-0 data-[closed]:zoom-out-95 data-[open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 w-72 origin-(--transform-origin) rounded-md border p-4 shadow-md outline-hidden',
            className
          )}
          {...props}
        />
      </Popover.Positioner>
    </Popover.Portal>
  )
}

function PopoverAnchor({ ...props }: React.ComponentProps<typeof Popover.Anchor>) {
  return <Popover.Anchor data-slot="popover-anchor" {...props} />
}

export { PopoverRoot as Popover, PopoverTrigger, PopoverContent, PopoverAnchor }
