// qwik-app/src/components/ui/progress/progress.tsx
import { cn } from "@qwik-ui/utils";
import { type PropsOf, component$ } from "@builder.io/qwik";
import { Progress as HeadlessProgress } from "@qwik-ui/headless";

export const Progress = component$<PropsOf<typeof HeadlessProgress.Root>>(
  (props) => {
    return (
      <HeadlessProgress.Root
        class={cn(
          "bg-muted relative h-4 w-full overflow-hidden rounded-sm border",
          props.class,
        )}
        {...props}
      >
        <HeadlessProgress.Indicator class="bg-primary h-full w-full flex-1 transition-all" />
      </HeadlessProgress.Root>
    );
  },
);

// web/src/components/ui/progress.tsx
'use client'

import { Progress } from '@base-ui/react/progress'
import type * as React from 'react'

import { cn } from '@/lib/utils'

function ProgressRoot({ className, value, ...props }: React.ComponentProps<typeof Progress.Root>) {
  return (
    <Progress.Root
      data-slot="progress"
      value={value}
      className={cn('bg-primary/20 relative h-2 w-full overflow-hidden rounded-full', className)}
      {...props}
    >
      <Progress.Track data-slot="progress-track" className="h-full w-full">
        <Progress.Indicator
          data-slot="progress-indicator"
          className="bg-primary h-full transition-all"
          style={{ width: `${value ?? 0}%` }}
        />
      </Progress.Track>
    </Progress.Root>
  )
}

export { ProgressRoot as Progress }
