// qwik-app/src/components/voice-waveform.tsx
import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";

interface VoiceWaveformProps {
  isRecording: boolean;
}

export const VoiceWaveform = component$<VoiceWaveformProps>((props) => {
  const bars = useSignal<number[]>(Array(20).fill(0.1));
  const analyserRef = useSignal<AnalyserNode | null>(null);
  const animationRef = useSignal<number | null>(null);

  useVisibleTask$(({ track, cleanup }) => {
    track(() => props.isRecording);

    if (!props.isRecording) {
      bars.value = Array(20).fill(0.1);
      if (animationRef.value !== null) {
        cancelAnimationFrame(animationRef.value);
        animationRef.value = null;
      }
      return;
    }

    // Create audio context and analyser when recording starts
    try {
      const audioContext = new AudioContext();
      const analyser = audioContext.createAnalyser();
      analyser.fftSize = 64;
      analyserRef.value = analyser;

      // Get the microphone stream
      navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
        audioContext.createMediaStreamSource(stream).connect(analyser);

        const dataArray = new Uint8Array(analyser.frequencyBinCount);

        const updateBars = () => {
          analyser.getByteFrequencyData(dataArray);
          const normalized = Array.from(dataArray.slice(0, 20)).map(
            (v) => Math.max(v / 128, 0.1)
          );
          bars.value = normalized;
          animationRef.value = requestAnimationFrame(updateBars);
        };

        animationRef.value = requestAnimationFrame(updateBars);
      });
    } catch {
      // Audio context creation failed
    }

    cleanup(() => {
      if (animationRef.value !== null) {
        cancelAnimationFrame(animationRef.value);
      }
    });
  });

  return (
    <div class="flex items-center justify-center gap-0.5 h-10 px-2 w-full">
      {bars.value.map((height, i) => (
        <div
          key={i}
          class="w-1 bg-red-500 rounded-full transition-all duration-75 ease-linear"
          style={{
            height: `${Math.max(height * 32, 4)}px`,
          }}
        />
      ))}
    </div>
  );
});

// web/src/components/voice-waveform.tsx
"use client";

import { useEffect, useRef } from "react";

const BARS = [
  { w: 2, base: 0.18 },
  { w: 2, base: 0.22 },
  { w: 3, base: 0.28 },
  { w: 2, base: 0.35 },
  { w: 3, base: 0.45 },
  { w: 2, base: 0.52 },
  { w: 3, base: 0.62 },
  { w: 2, base: 0.70 },
  { w: 3, base: 0.78 },
  { w: 2, base: 0.84 },
  { w: 3, base: 0.90 },
  { w: 2, base: 0.94 },
  { w: 3, base: 0.97 },
  { w: 2, base: 0.99 },
  { w: 3, base: 1.00 },
  { w: 3, base: 1.00 },
  { w: 2, base: 0.99 },
  { w: 3, base: 0.97 },
  { w: 2, base: 0.94 },
  { w: 3, base: 0.90 },
  { w: 2, base: 0.84 },
  { w: 3, base: 0.78 },
  { w: 2, base: 0.70 },
  { w: 3, base: 0.62 },
  { w: 2, base: 0.52 },
  { w: 3, base: 0.45 },
  { w: 2, base: 0.35 },
  { w: 3, base: 0.28 },
  { w: 2, base: 0.22 },
  { w: 2, base: 0.18 },
] as const;

const MIN_H = 3;
const MAX_H = 32;

interface VoiceWaveformProps {
  stream: MediaStream;
}

export function VoiceWaveform({ stream }: VoiceWaveformProps) {
  const barsRef = useRef<(HTMLDivElement | null)[]>([]);
  const animRef = useRef<number>(0);

  useEffect(() => {
    let audioCtx: AudioContext | null = null;
    let source: MediaStreamAudioSourceNode | null = null;
    let analyser: AnalyserNode | null = null;

    try {
      audioCtx = new AudioContext();
      analyser = audioCtx.createAnalyser();
      analyser.fftSize = 128;
      analyser.smoothingTimeConstant = 0.75;
      source = audioCtx.createMediaStreamSource(stream);
      source.connect(analyser);
    } catch {
      return;
    }

    const data = new Uint8Array(analyser.frequencyBinCount);

    const tick = () => {
      animRef.current = requestAnimationFrame(tick);
      analyser!.getByteFrequencyData(data);

      barsRef.current.forEach((bar, i) => {
        if (!bar) return;
        const cfg = BARS[i];
        // Sample from vocal frequency range (~85–3000 Hz, lower half of bins)
        const idx = Math.floor((i / BARS.length) * data.length * 0.55);
        const energy = data[idx] / 255;
        // Modulate envelope: base shape * audio energy, with a floor so bars are always visible
        const h = MIN_H + cfg.base * energy * (MAX_H - MIN_H) + cfg.base * 4;
        bar.style.height = `${h}px`;
        bar.style.opacity = String(0.3 + cfg.base * 0.4 + energy * 0.3);
      });
    };

    tick();

    return () => {
      cancelAnimationFrame(animRef.current);
      source?.disconnect();
      audioCtx?.close();
    };
  }, [stream]);

  return (
    <div className="flex items-center gap-2 px-1 py-2 min-h-[44px]">
      {/* Live indicator */}
      <span className="relative flex h-2 w-2 shrink-0 ml-1">
        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-60" />
        <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />
      </span>

      {/* Waveform bars */}
      <div className="flex flex-1 items-center justify-center gap-[3px]">
        {BARS.map((cfg, i) => (
          <div
            key={i}
            ref={(el) => {
              barsRef.current[i] = el;
            }}
            className="rounded-full bg-foreground transition-[height] duration-75 ease-out"
            style={{
              width: cfg.w,
              height: MIN_H + cfg.base * 4,
              opacity: 0.3 + cfg.base * 0.4,
            }}
          />
        ))}
      </div>

      {/* Spacer matching the ping dot so bars stay centered */}
      <span className="h-2 w-2 shrink-0 mr-1" />
    </div>
  );
}
